### ISSUE TITLE
[New submission] Movie Country Icons - Flags

### ISSUE THREAD

**Issue by braz96** [xbmc/repo-resources#13]
**- Add-on name:** Movie Country Icons - Flags
 **- Add-on ID:** resource.images.moviecountryicons.flags
 **- Version number:** 0.0.1
 **- Kodi/repository version:** Jarvis
 **- Code location URL:** https://github.com/braz96/resource.images.moviecountryicons.flags
 **- Revision/tag:** cc950794c68a6b7b461ec2c4ce9602a05a4c4c3e
 **- Branch:** master

This addon requires skin implementation. Since this is typically done by comparing the infolabel to the filename, I set compile to false so users can rename the images to match their language if needed. Let me know if there is a better approach or if any other changes are needed. Thanks!

**Comment by ronie** [comment]
nope, i don't think there's a better way to handle it.
so leaving compile as false should be ok here.

you might want to fix the `<source>` in the addon.xml file as it currently points to your skin :-)

also, please check the filename of these two:
https://github.com/braz96/resource.images.moviecountryicons.flags/blob/master/resources/Cura%C3%83%C2%A7ao.png
https://github.com/braz96/resource.images.moviecountryicons.flags/blob/master/resources/C%C3%83%C2%B4te%20d'Ivoire.png

**Comment by braz96** [comment]
Thanks Ronie, here's the new commit...

5767c11b9befe8bc109d331d02313e8db3b13ae1

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-resources/commit/348eeca5fc6fe1a6fc3ca9fc8b7816bab97bdee7
