### ISSUE TITLE
[New submission] Movie Country Icons - Maps

### ISSUE THREAD

**Issue by braz96** [xbmc/repo-resources#14]
**- Add-on name:** Movie Country Icons - Maps
 **- Add-on ID:** resource.images.moviecountryicons.maps
 **- Version number:** 0.0.1
 **- Kodi/repository version:** Jarvis
 **- Code location URL:** https://github.com/braz96/resource.images.moviecountryicons.maps
 **- Revision/tag:** 68cf8917955cf8d70688e830be9687def9f9f10d
 **- Branch:** master

Here's another image resource addon for the Countries node.

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-resources/commit/e090ae1f165ff060a8fae7a3c889e1a0009e4a5a
