### ISSUE TITLE
[Update] resource.images.weathericons.monstr

### ISSUE THREAD

**Issue by braz96** [xbmc/repo-resources#15]
### Add-on details:

- **General**
  - Add-on name: Weather Icons - Monstr
  - Add-on ID: resource.images.weathericons.monstr
  - Version number: 0.0.2
  - Kodi/repository version: Jarvis

- **Code location**
  - URL: https://github.com/braz96/resource.images.weathericons.monstr
  - Revision/tag: a56ece7ac2ba830256844de1412d441fb5c45950
  - Branch: master

### Description of changes:
Updated several icons to more closely match the list of weather codes recently posted on the wiki.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-resources/commit/bd760e5a92abdac7170cf7d985fa28d049bee474
