### ISSUE TITLE
Weather Icons - HD Animated

### ISSUE THREAD

**Issue by kyokusa** [xbmc/repo-resources#17]
### Add-on details:

- **General**
  - Add-on name: Weather Icons - HD Animated
  - Add-on ID: resource.images.weathericons.HD.animated
  - Version number: v1.0.0
  - Kodi/repository version: Jarvis

- **Code location**
  - URL: https://github.com/kyokusa/WeatherIconsHDAnimated/releases/tag/v1.0.0
  - Revision/tag: 
  - Branch: master

### Checklist:

- [ ] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [ ] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [ ] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
the provided zipfile contains a Textures.xbt file, but we need to uncompressed source images.

the resources folder in your repo only contains 1 image, so can't use that either :-)

**Comment by kyokusa** [comment]
Hi Ronie, i had imagined, GitHub unfortunately does not allow me to upload more than 100MB, so I send you (thanking you advance) still have a link with the original image file is 166MB.

https://mega.nz/#!F4lBjJ5Y!O8m8ZpyJTRasRD6G99xlfFhRJx5s-sB9BilGz8rzAO4

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-resources/commit/add2df3b987f4cfa59a4cb2e9ac0e0aa103a60f6
