### ISSUE TITLE
[new submission] resource.images.skinicons.wide

### ISSUE THREAD

**Issue by marcelveldt** [xbmc/repo-resources#20]
- Add-on name: Skin Icons Pack - Wide
- Add-on ID: resource.images.skinicons.titan
- Version number: 1.0.2
- Kodi/repository version: Jarvis
- URL: https://github.com/marcelveldt/resource.images.skinicons.wide
- Revision/tag: latest
- Branch: master

### Description of changes:
Image resource addon with landscaped icons which can be used by skins.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-resources/commit/219f62a7b0ba5ebe185a4c5d7e2fb6ed773bfaa8
