### ISSUE TITLE
[new submission] resource.skinthemes.titan

### ISSUE THREAD

**Issue by marcelveldt** [xbmc/repo-resources#21]
- Add-on name: Titan skin Themes
- Add-on ID: resource.skinthemes.titan
- Version number: 1.0.2
- Kodi/repository version: Jarvis
- URL: https://github.com/marcelveldt/resource.skinthemes.titan

- Revision/tag: latest
- Branch: master

### Description of changes:
Kodi resource addon with additional skin themes for the Titan skin.
Not exactly a resource addon containing images so I'm not sure if this is accepted this way. I found it a good idea to move all static stuff out of the skin's directory and move it to resource addons.

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document

**Comment by ronie** [comment]
> Not exactly a resource addon containing images so I'm not sure if this is accepted this way.

nope, i'm afraid not.
a resource addon should be a shared resource, that can be used by any skin.
it's not intended to be used for skin specific items.

**Comment by marcelveldt** [comment]
Ah, that's too bad. In that case let me quickly merge the files back in the skin then.

**Comment by marcelveldt** [comment]
@ronie all set. I've moved the files back to the skin.

**Comment by marcelveldt** [comment]
@ronie any word on my PR's ? Anything I can do to help ?

**Comment by marcelveldt** [comment]
btw this one can be closed

**Comment by ronie** [comment]
> @ronie any word on my PR's ? Anything I can do to help ?

sorry for the lengthy delay, i'll review them now :)

**Comment by marcelveldt** [comment]
no problem ronie, thanks !
