### ISSUE TITLE
[new submission] resource.images.backgroundoverlays.basic

### ISSUE THREAD

**Issue by marcelveldt** [xbmc/repo-resources#22]
- Add-on name: Basic Background Overlays Pack
- Add-on ID: resource.images.backgroundoverlays.basic
- Version number: 1.0.0
- Kodi/repository version: Jarvis
- URL: https://github.com/marcelveldt/resource.images.backgroundoverlays.basic
- Revision/tag: latest
- Branch: master

### Description of changes:
Pack of images that can be used as background overlay

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document

**Comment by ronie** [comment]
added, thx!

**Comment by ronie** [comment]
https://github.com/xbmc/repo-resources/commit/9b94a1a31181eff7b151cc1363d129eb9315d09a
