### ISSUE TITLE
[new submission] resource.images.busyspinners.basic

### ISSUE THREAD

**Issue by marcelveldt** [xbmc/repo-resources#23]
- Add-on name: Animated Busy Spinners Pack - Basic
- Add-on ID: resource.images.busyspinners.basic
- Version number: 1.0.0
- Kodi/repository version: Jarvis
- URL: https://github.com/marcelveldt/resource.images.busyspinners.basic
- Revision/tag: latest
- Branch: master

### Description of changes:
Pack of images that can be used as busy spinner

### Checklist:
- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-resources/commit/b2fb7bf49768ef5f643f2d6c8d95537d6f531553
