### ISSUE TITLE
[New] resource.images.languageflags.colour-flat

### ISSUE THREAD

**Issue by jeroenpardon** [xbmc/repo-resources#24]
### Add-on details:
- **General**
  - Add-on name: Language Flags Colour Flat
  - Add-on ID: resource.images.languageflags.colour-flat
  - Version number: 0.0.1
  - Kodi/repository version: Krypton

- **Code location**
  - URL: https://github.com/jeroenpardon/resource.images.languageflags.colour-flat
  - Revision/tag: a0184bb4fe601bb9161827b91bf5c2fa30f60ac4
  - Branch: master

### Description of changes:
First submission

### Checklist:
- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-skins/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-resources/commit/7d7d89dc3ed0c1224d5ac522e973185d7063ce03
