### ISSUE TITLE
Videolina

### ISSUE THREAD

**Issue by NextStepUnione** [xbmc/repo-resources#27]
### Add-on details:

- **General**
  - Add-on name: Videolina
  - Add-on ID: plugin.video.videolina
  - Version number: 1.0.0
  - Kodi/repository version: Isengard

- **Code location**
  - URL: https://github.com/NextStepUnione/plugin.video.videolina
  - Revision/tag: ba6171cb35a35507053e5f2f884adb848377b636
  - Branch: master

### Description of changes:
Watch live streaming of Videolina TV

### Checklist:

- [X] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [X] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [X] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by MartijnKaijser** [comment]
You need the Plugin repo

**Comment by NextStepUnione** [comment]
Could you explain what I have to do? Doesn't the repo that I have linked (https://github.com/NextStepUnione/plugin.video.videolina?files=1) contain all files to zip to obtain the plugin?

Fabiano Serra

On 3 Apr 2017, at 17:54, Martijn Kaijser <notifications@github.com<mailto:notifications@github.com>> wrote:

EMAIL MANDATA A NEXTSTEP@NEXTSTEP.IT<mailto:NEXTSTEP@NEXTSTEP.IT>

You need the Plugin repo

**Comment by ronie** [comment]
please submit your PR here: https://github.com/xbmc/repo-plugins
