### ISSUE TITLE
[Initial Submission] resource.uisounds.appletv

### ISSUE THREAD

**Issue by fastcolors** [xbmc/repo-resources#37]
### Add-on details:

- **General**
  - Add-on name: AppleTV UI Sounds
  - Add-on ID: resource.uisounds.appletv
  - Version number: 0.0.1
  - Kodi/repository version: Krypton/Leia

- **Code location**
  - URL: https://github.com/fastcolors/resource.uisounds.appletv
  - Revision/tag: 0822bab  
  - Branch: master

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

**Comment by ronie** [comment]
hey @fastcolors , could you have a look at these issues:
- NavigateVideoNav.wav is unused, please remove.
- bump.wav is missing, please add.

**Comment by fastcolors** [comment]
should be fixed now

rev: [5ecdfc8](https://github.com/fastcolors/resource.uisounds.appletv/commit/5ecdfc8f6fa80de96a4143ba18a0ccdbc24faa7a)

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-resources/commit/b0261b9d7426b0ccaddb155c2e2a655cdc704aaa

**Comment by MartijnKaijser** [comment]
@fastcolors missing an icon.png in the addon

**Comment by ronie** [comment]
@fastcolors just noticed there's a typo in the addon id:
https://github.com/xbmc/repo-resources/commit/b0261b9d7426b0ccaddb155c2e2a655cdc704aaa#diff-07ce7a3344de746389abe007b401f319R2

two p's in appletv should be enough ;-)

can you correct that and submit a new pull-request?

**Comment by fastcolors** [comment]
😂😂😂

will fix it asap!!

**Comment by fastcolors** [comment]
done

https://github.com/fastcolors/resource.uisounds.appletv/commit/a4e9efc443633d5cfc5203727942612457034051

**Comment by ronie** [comment]
great, thx!
https://github.com/xbmc/repo-resources/commit/e481356efe4ff499df97b05c88dd37de899d2c2d
