### ISSUE TITLE
[New Submission] resource.images.classificationicons.colour

### ISSUE THREAD

**Issue by wyrm65** [xbmc/repo-resources#77]
### Add-on details:

- **General**
  - Add-on name: Classification Icons - Colour
  - Add-on ID: resource.images.classificationicons.colour
  - Version number: 0.0.1
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/wyrm65/resource.images.classificationicons.colour
  - Revision/tag: 8597d3aa803b984d7af6ebe6e976e13a41999947
  - Branch: master

### Description of changes:

Provides a collection of square aspect ratio video classification icons from around the world. This is my attempt to set a standard to provide classification icon images for use in Kodi media centre skins. By providing a standard naming scheme for the images it is my hope that this will become the standard way for Kodi skins to support more than a tiny subset of available classification icons.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
mind modernizing the addon.xml file a bit?
- use: lang="en_GB"
- add an `<assets>` section for the icon and fanart image

for the rest, looks good to me, thx!

**Comment by wyrm65** [comment]
Sorry mate, dangers of cut and paste. Please try

33d3a00af25e818140eac96fdf2f2bce83b18975

**Comment by KarellenX** [comment]
Noticed a typ-o

**Rusia 12+.png**

**Comment by wyrm65** [comment]
Thanks for the catch KarellenX.

ronie please update to f130d935aef80dccd4a8740e96135dcc3d5a232d

**Comment by ronie** [comment]
added, thx!
https://github.com/xbmc/repo-resources/commit/4cf6ec068a7eea4e6c1010ae3d41f7cd181dcb5d
