### ISSUE TITLE
[Update] resource.images.classificationicons.colour

### ISSUE THREAD

**Issue by wyrm65** [xbmc/repo-resources#96]
### Add-on details:

- **General**
  - Add-on name: Classification Icons - Colour
  - Add-on ID: resource.images.classificationicons.colour
  - Version number: 0.0.3
  - Kodi/repository version: Leia

- **Code location**
  - URL: https://github.com/wyrm65/resource.images.classificationicons.colour
  - Revision/tag: 5b2bf0b4b9814700ef60efd384913619d839254d
  - Branch: master

### Description of changes:

Changes since initial release

v0.0.3
- Add alternate naming of Spanish files to allow for Embuary skin helper script returning (12Horas) or (24Horas) at end of country name.
- Add a number of alternate image names to allow for different results supplied by scrappers. For example MA15+ for Australian MA certification. 
- Update Readme.md file to show current supported countrys and revisied usage instructions.

v0.0.2
- Add additional country icons.
- Change naming of some files to make it easier for scappers to support naming scheme.

### Checklist:

- [x] My code follows the [add-on rules](http://kodi.wiki/view/Add-on_rules) and [piracy stance](http://kodi.wiki/view/Official:Forum_rules#Piracy_Policy) of this project. 
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/repo-resources/blob/master/CONTRIBUTING.md) document
- [x] Each add-on submission should be a single commit with using the following style: [plugin.video.foo] v1.0.0

Additional information :
- Submitting your add-on to this specific branch makes it available to any Kodi version equal or higher than the branch name with the applicable Kodi dependencies limits.
- [add-on development](http://kodi.wiki/view/Add-on_development) wiki page.
- Kodi [pydocs](http://kodi.wiki/view/PyDocs) provide information about the Python API
- [PEP8](https://www.python.org/dev/peps/pep-0008/) codingstyle which is considered best practice but not mandatory.
- This add-on repository has automated code guideline check which could help you improve your coding. You can find the results of these check at [Codacy](https://www.codacy.com/app/Kodi/repo-plugins/dashboard). You can create your own account as well to continuously monitor your python coding before submitting to repo.
- Development questions can be asked in the [add-on development](http://forum.kodi.tv/forumdisplay.php?fid=26) section on the Kodi forum.

**Comment by ronie** [comment]
updated, thx!
https://github.com/xbmc/repo-resources/commit/70ca71f54aa13e6c414b307a92deb2363b3ff180
